# Assignment-3 — UCS420 Cognitive Computing (Pandas)

This notebook contains complete Python solutions for Questions 1–6.  
All cells are written to run in a normal Python/Jupyter environment without requiring internet access. For Q4–Q5, if the Kaggle `Iris.csv` file is not present, a local Iris CSV is created automatically from scikit-learn so the code can still run.

## Q1. Create the dataset

In [1]:
import pandas as pd

data = {
    "Tid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
    "Marital Status": ["Single", "Married", "Single", "Married", "Divorced",
                       "Married", "Divorced", "Single", "Married", "Single"],
    "Taxable Income": ["125K", "100K", "70K", "120K", "95K",
                       "60K", "220K", "85K", "75K", "90K"],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)
df

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

## Q2. Locate rows 0, 4, 7 and 8

In [2]:
selected_rows = df.iloc[[0, 4, 7, 8]]
selected_rows

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

## Q3. Navigate the DataFrame

### Q3.1 Select rows from index 3 to 7

In [3]:
rows_3_to_7 = df.iloc[3:8]
rows_3_to_7

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

### Q3.2 Select rows from index 4 to 8 and columns 2 to 4

In [4]:
rows_4_to_8_cols_2_to_4 = df.iloc[4:9, 2:5]
rows_4_to_8_cols_2_to_4

  Marital Status Taxable Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No

### Q3.3 Select all rows with column index 1 to 3, including column index 3

In [5]:
cols_1_to_3 = df.iloc[:, 1:4]
cols_1_to_3

  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

## Q4. Read a CSV file and display its first five rows

In [6]:
import os

iris_file = "Iris.csv"

# If the Kaggle Iris.csv is not available, create a local Iris CSV
# so that the remaining code runs without an internet connection.
if not os.path.exists(iris_file):
    try:
        from sklearn.datasets import load_iris

        iris = load_iris()
        iris_df = pd.DataFrame(
            iris.data,
            columns=["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]
        )
        iris_df["Species"] = [iris.target_names[i] for i in iris.target]
        iris_df.insert(0, "Id", range(1, len(iris_df) + 1))
        iris_df.to_csv(iris_file, index=False)
    except ImportError:
        raise FileNotFoundError(
            "Iris.csv was not found. Download the Kaggle Iris dataset and place Iris.csv "
            "in the same folder as this notebook."
        )

iris_df = pd.read_csv(iris_file)
iris_df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0   1            5.1           3.5            1.4           0.2  setosa
1   2            4.9           3.0            1.4           0.2  setosa
2   3            4.7           3.2            1.3           0.2  setosa
3   4            4.6           3.1            1.5           0.2  setosa
4   5            5.0           3.6            1.4           0.2  setosa

## Q5. Delete row 4 and column 3 from the CSV data

In [7]:
# Delete row at index 4 and column at positional index 3
iris_modified = iris_df.drop(index=iris_df.index[4])
iris_modified = iris_modified.drop(columns=iris_modified.columns[3])

iris_modified

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm    Species
0      1            5.1           3.5           0.2     setosa
1      2            4.9           3.0           0.2     setosa
2      3            4.7           3.2           0.2     setosa
3      4            4.6           3.1           0.2     setosa
5      6            5.4           3.9           0.4     setosa
..   ...            ...           ...           ...        ...
145  146            6.7           3.0           2.3  virginica
146  147            6.3           2.5           1.9  virginica
147  148            6.5           3.0           2.0  virginica
148  149            6.2           3.4           2.3  virginica
149  150            5.9           3.0           1.8  virginica

[149 rows x 5 columns]

## Q6. Create `employees.csv` and perform the required operations

In [8]:
employee_data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

employees = pd.DataFrame(employee_data)
employees["Joining_Date"] = pd.to_datetime(employees["Joining_Date"])

employees.to_csv("employees.csv", index=False)
employees

   Employee_ID     Name Department  Age  ...  Joining_Date  Gender Bonus Rating
0          101    Alice         HR   29  ...    2020-03-15  Female  5000    4.5
1          102      Bob         IT   34  ...    2017-07-19    Male  7000    4.0
2          103  Charlie         IT   41  ...    2013-06-01    Male  6000    3.8
3          104    Diana  Marketing   28  ...    2021-02-10  Female  4500    4.7
4          105   Edward      Sales   38  ...    2010-11-25    Male  5000    3.5

[5 rows x 10 columns]

### Q6(a). Shape of the DataFrame

In [9]:
shape = employees.shape
print("Number of rows:", shape[0])
print("Number of columns:", shape[1])

Number of rows: 5
Number of columns: 10

### Q6(b). Data types and non-null counts

In [10]:
summary = pd.DataFrame({
    "Data Type": employees.dtypes.astype(str),
    "Non-Null Count": employees.notna().sum()
})
summary

                          Data Type  Non-Null Count
Employee_ID                   int64               5
Name                         object               5
Department                   object               5
Age                           int64               5
Salary                        int64               5
Years_of_Experience           int64               5
Joining_Date         datetime64[ns]               5
Gender                       object               5
Bonus                         int64               5
Rating                      float64               5

### Q6(c). Descriptive statistics

In [11]:
employees.describe()

       Employee_ID        Age  ...   Bonus    Rating
count     5.000000   5.000000  ...     5.0  5.000000
mean    103.000000  34.000000  ...  5500.0  4.100000
min     101.000000  28.000000  ...  4500.0  3.500000
25%     102.000000  29.000000  ...  5000.0  3.800000
50%     103.000000  34.000000  ...  5000.0  4.000000
75%     104.000000  38.000000  ...  6000.0  4.500000
max     105.000000  41.000000  ...  7000.0  4.700000
std       1.581139   5.612486  ...  1000.0  0.494975

[8 rows x 7 columns]

### Q6(d). First 5 rows and last 3 rows

In [12]:
print("First 5 rows:")
display(employees.head(5))

print("Last 3 rows:")
display(employees.tail(3))

First 5 rows:

   Employee_ID     Name Department  Age  ...  Joining_Date  Gender Bonus Rating
0          101    Alice         HR   29  ...    2020-03-15  Female  5000    4.5
1          102      Bob         IT   34  ...    2017-07-19    Male  7000    4.0
2          103  Charlie         IT   41  ...    2013-06-01    Male  6000    3.8
3          104    Diana  Marketing   28  ...    2021-02-10  Female  4500    4.7
4          105   Edward      Sales   38  ...    2010-11-25    Male  5000    3.5

[5 rows x 10 columns]

Last 3 rows:

   Employee_ID     Name Department  Age  ...  Joining_Date  Gender Bonus Rating
2          103  Charlie         IT   41  ...    2013-06-01    Male  6000    3.8
3          104    Diana  Marketing   28  ...    2021-02-10  Female  4500    4.7
4          105   Edward      Sales   38  ...    2010-11-25    Male  5000    3.5

[3 rows x 10 columns]

### Q6(e). Required statistics

In [13]:
average_salary = employees["Salary"].mean()
total_bonus = employees["Bonus"].sum()
youngest_age = employees["Age"].min()
highest_rating = employees["Rating"].max()

print("Average salary:", average_salary)
print("Total bonus paid:", total_bonus)
print("Youngest employee's age:", youngest_age)
print("Highest performance rating:", highest_rating)

Average salary: 60000.0
Total bonus paid: 27500
Youngest employee's age: 28
Highest performance rating: 4.7

### Q6(f). Sort by Salary in descending order

In [14]:
sorted_employees = employees.sort_values(by="Salary", ascending=False)
sorted_employees

   Employee_ID     Name Department  Age  ...  Joining_Date  Gender Bonus Rating
1          102      Bob         IT   34  ...    2017-07-19    Male  7000    4.0
2          103  Charlie         IT   41  ...    2013-06-01    Male  6000    3.8
4          105   Edward      Sales   38  ...    2010-11-25    Male  5000    3.5
3          104    Diana  Marketing   28  ...    2021-02-10  Female  4500    4.7
0          101    Alice         HR   29  ...    2020-03-15  Female  5000    4.5

[5 rows x 10 columns]

### Q6(g). Add Performance_Category

In [15]:
def performance_category(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

employees["Performance_Category"] = employees["Rating"].apply(performance_category)
employees

   Employee_ID     Name Department  ...  Bonus  Rating  Performance_Category
0          101    Alice         HR  ...   5000     4.5             Excellent
1          102      Bob         IT  ...   7000     4.0                  Good
2          103  Charlie         IT  ...   6000     3.8               Average
3          104    Diana  Marketing  ...   4500     4.7             Excellent
4          105   Edward      Sales  ...   5000     3.5               Average

[5 rows x 11 columns]

### Q6(h). Identify missing values

In [16]:
missing_values = employees.isnull().sum()
missing_values

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

### Q6(i). Rename `Employee_ID` to `ID`

In [17]:
employees.rename(columns={"Employee_ID": "ID"}, inplace=True)
employees

    ID     Name Department  Age  ...  Gender  Bonus Rating Performance_Category
0  101    Alice         HR   29  ...  Female   5000    4.5            Excellent
1  102      Bob         IT   34  ...    Male   7000    4.0                 Good
2  103  Charlie         IT   41  ...    Male   6000    3.8              Average
3  104    Diana  Marketing   28  ...  Female   4500    4.7            Excellent
4  105   Edward      Sales   38  ...    Male   5000    3.5              Average

[5 rows x 11 columns]

### Q6(j). Find employees with more than 5 years of experience and employees in IT

In [18]:
more_than_5_years = employees[employees["Years_of_Experience"] > 5]
it_employees = employees[employees["Department"] == "IT"]

print("Employees with more than 5 years of experience:")
display(more_than_5_years)

print("Employees in the IT department:")
display(it_employees)

Employees with more than 5 years of experience:

    ID     Name Department  Age  ...  Gender  Bonus Rating Performance_Category
1  102      Bob         IT   34  ...    Male   7000    4.0                 Good
2  103  Charlie         IT   41  ...    Male   6000    3.8              Average
4  105   Edward      Sales   38  ...    Male   5000    3.5              Average

[3 rows x 11 columns]

Employees in the IT department:

    ID     Name Department  Age  ...  Gender  Bonus Rating Performance_Category
1  102      Bob         IT   34  ...    Male   7000    4.0                 Good
2  103  Charlie         IT   41  ...    Male   6000    3.8              Average

[2 rows x 11 columns]

### Q6(k). Add Tax column (10% of Salary)

In [19]:
employees["Tax"] = employees["Salary"] * 0.10
employees

    ID     Name Department  Age  ...  Bonus  Rating Performance_Category     Tax
0  101    Alice         HR   29  ...   5000     4.5            Excellent  5000.0
1  102      Bob         IT   34  ...   7000     4.0                 Good  7000.0
2  103  Charlie         IT   41  ...   6000     3.8              Average  6500.0
3  104    Diana  Marketing   28  ...   4500     4.7            Excellent  5500.0
4  105   Edward      Sales   38  ...   5000     3.5              Average  6000.0

[5 rows x 12 columns]

### Q6(l). Save the modified DataFrame to a new CSV file

In [20]:
output_file = "employees_modified.csv"
employees.to_csv(output_file, index=False)

print(f"Modified DataFrame saved as: {output_file}")
print(f"File exists: {os.path.exists(output_file)}")

Modified DataFrame saved as: employees_modified.csv
File exists: True